---
- name: testing a taskfile include
  hosts: all
  vars_prompt:
  - name: should_i_include
    prompt: Should I include the file? (Yes/No) 
    private: false
    default: yes
  gather_facts: no
  tasks:
  - name: include taskfile_to_be_included.yml
    include_tasks: taskfile_to_be_included.yml
    vars:
      message1: "Ez egy uzenet"
      message2: "Mutatok valamit"
    when: should_i_include


