---
- name: test webserver access
  hosts: localhost
  become: no
  tasks:
  - name: connect to web server
    uri:
      url: http://client2
      return_content: yes
    register: this
    failed_when: "'welcome' not in this.content"
  - name: show result
    debug:
      var: this.content



