---
- name: |
    .
    Using group and users modules
    and template to set up sudo file
    .
  hosts: client2
  tasks:
  - name: set up the group account
    group:
      name: students
      state: present
  - name: set up the user account
    user:
      name: anna
      create_home: yes
      groups: wheel,students
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    
