
---
- name: display custom facts
  hosts: client2
  tasks:
    - name: show it now
      debug:
        var: ansible_facts['ansible_local']['exercise61']['software']
- name: install and start a web service
  hosts: client2
  tasks:
    - name: install package
      yum:
        name: "{{ ansible_facts['ansible_local']['exercise61']['software']['package'] }}"
    - name: start the service
      service:
        name: "{{ ansible_facts['ansible_local']['exercise61']['software']['service'] }}"
        state: "{{ ansible_facts['ansible_local']['exercise61']['software']['state'] }}"
        enabled: "{{ ansible_facts['ansible_local']['exercise61']['software']['enabled'] }}"

