
---
- name: create a user with data from a vault
  hosts: client2
  vars_files:
    - exercise6.3.vault
  tasks:
  - name: creating user
    user:
      name: "{{ username }}"
      password: "{{ pwhash }}"

