---
- name: restart sshd servive if httpd is running
  hosts: client1
  tasks:
  - name: get httpd service status
    command: systemctl is-active httpd
    ignore_errors: yes
    register: result
  - name: show registered variable contens
    debug:
      msg: printing contents of the registered variable {{ result }}
  - name: restart sshd conditionally
    service:
      name: sshd
      state: restarted
    when: result.rc == 0


