
---
- name: install and enable services
  hosts: client1
  tasks:
  # YUM module can handle package lists as input
  - name: install packages
    yum:
      name:
      - vsftpd
      - httpd
      - samba
      state: latest
  # SERVICE module can NOT handle lists of services, therefore loop is needed
  - name: start the services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:   # could be "with_items" or "with_list" too
    - vsftpd
    - httpd
    - smb

