
# a handler csak akkor fut le, ha elotte minden lefutott jol
# EEES a vonatkozo task CHANGED statusszal er veget


---
- name: create file on localhosts
  hosts: localhost
  tasks:
  - name: create index.html.on localhost
    copy:
      content: "welcome to the webserver"
      dest: /tmp/index.html

- name: set up web server
  hosts: all
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: copy index.html
    copy:
      src: /tmp/index.html
      dest: /var/www/html/index.html
    notify:
      - restart_web
  - name: copy nothing - intended to fail
    copy:
      src: /tmp/nothing
      dest: /var/www/html/nothing.html

  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted

