---
- name: install httpd package
  hosts: all
  gather_facts: no
  tasks:
  - name: install package
    package:
      name: httpd
      state: installed
- name: start and enable httpd
  hosts: all
  tasks:
  - name: start and enable httpd
    service:
      name: httpd
      state: started
      enabled: yes
