
---
- name: file copy modules
  hosts: all
  tasks:
  - name: copy file demo
    copy:
      src: /etc/hosts
      dest: /tmp/
  - name: add some lines to /tmp/hosts
    blockinfile:
      path: /tmp/hosts
      block: |
        192.168.4.110 host1.example.com
        192.168.4.120 host2.example.com
      marker: '# {mark} TRIFO MANAGED SECTION'
      state: present
  - name: verify checksums
    stat:
      path: /tmp/hosts
      checksum_algorithm: sha512
    register: result
  - debug:
      msg: " The checksum of /tmp/hosts is {{ result.stat.checksum }}"
  - name: fetch a file
    fetch:
      src: /tmp/hosts
      dest: /tmp/

