---
- name: Manage SELinux policy example
  hosts: client1
  vars:
    # Use "targeted" SELinux policy type
    selinux_policy: targeted
    # Set "enforcing" mode
    selinux_state: enforcing
    # Switch some SELinux booleans
    selinux_booleans:
      # Set the 'ssh_sysadm_login' boolean to 'on' permanently
      - name: cron_can_relabel
        state: true
        persistent: true
    # Map '/tmp/test_dir' and its subdirectories to the 'user_home_dir_t'
    # SELinux file type
    selinux_fcontexts:
      - target: '/var/ftp/anonuploads(/.*)?'
        setype: public_content_rw_t
        ftype: d
        state: present
    # Restore SELinux file contexts in '/tmp/test_dir'
    selinux_restore_dirs:
      - /var/ftp/anonuploads
    # Map tcp port 22100 to the 'ssh_port_t' SELinux port type
    selinux_ports:
      - ports: 82
        proto: tcp
        setype: http_port_t
        state: present
  tasks:
    - name: Creates directory
      file:
        path: /var/ftp/anonuploads
        state: directory
        mode: "0777"

    - name: Execute the role and reboot in a rescue block
      block:
        - name: Include selinux role
          include_role:
            name: rhel-system-roles.selinux
      rescue:
        - name: >-
            Fail if failed for a different reason than selinux_reboot_required
          fail:
            msg: "role failed"
          when: not selinux_reboot_required

        - name: Restart managed host
          reboot:

        - name: Wait for managed host to come back
          wait_for_connection:
            delay: 10
            timeout: 300

        - name: Reapply the role
          include_role:
            name: rhel-system-roles.selinux
